// import { GoogleSpreadsheet } from 'google-spreadsheet'
// import { JWT } from 'google-auth-library'

// const Sheet = async () => {
//   const serviceAccountAuth = new JWT({
//     // env var values here are copied from service account credentials generated by google
//     // see "Authentication" section in docs for more info
//     email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
//     key: process.env.GOOGLE_PRIVATE_KEY,
//     scopes: ['https://www.googleapis.com/auth/spreadsheets'],
//   })
//   const doc = new GoogleSpreadsheet(
//     '1K_GzkqAp08QRJ5j09B9fVWtXR4y2SicWVJejqqilcEk',
//     serviceAccountAuth,
//   )
//   return doc
// }

// export default Sheet
